### ISSUE TITLE
simple image rotation

### ISSUE THREAD

**Issue by msmzuppa** [Foliotek/Croppie#104]
I need help using croppie, i'm trying to rotate the image but how do you do it in croppie??

**Comment by thedustinsmith** [comment]
Currently there's no way to rotate an manually using croppie.  If it's an image that has exif rotational data attached to it, you can use the `exif` boolean documented here: http://foliotek.github.io/Croppie/#documentation.

Otherwise if you're just talking about having a function to call to rotate the image a certain amount of degrees, that doesn't exist yet - but has already been requested in #86.

**Comment by thedustinsmith** [comment]
#105 will fix this one.

**Comment by thedustinsmith** [comment]
You can rotate the image with `croppieInstance.rotate(90)` with version 2.1.0.  It's documented in the API.
