### ISSUE TITLE
Croppie is over-zooming my images. any sugguestions?

### ISSUE THREAD

**Issue by st443** [Foliotek/Croppie#122]
See stack overflow question here: http://stackoverflow.com/questions/36585306/how-to-prevent-over-zooming-with-croppie-javascript-image-cropping-plugin

**Comment by thedustinsmith** [comment]
Is your croppie container inside of a modal of some sort?  If so, you need to call `bind` after the modal has been shown.

If not, there may be a problem in croppie.  Because it's supposed to set the minimum zoom so that the image can be no smaller than the viewport, but your image looks at least the size of your boundary (if not larger) and your zoom slider looks like it's on the min value.

If you can throw together an jsbin or jsfiddle we can look at, it might be easier to track down.

**Comment by st443** [comment]
I think I figured it out. After commenting out the "bind" call, it behaves as I would expect. Strange..
`$('#upload-avatar').croppie({
                    viewport: {
                        width: 100,
                        height: 100,
                        type: 'square' 
                    },
                    url: json.file
                });
\//$('#upload-avatar').croppie('bind');`

**Comment by thedustinsmith** [comment]
That is strange - Thanks for pointing it out.  I'll have to look into that.  I would say bind shouldn't do anything if it's already been bound.

**Comment by thedustinsmith** [comment]
I'm pretty sure this was caused by another error.  I recreated your scenario on the demo page, and the extra `bind()` call didn't cause a weird zoom effect.  

I'm going to go ahead and close this one.
