### ISSUE TITLE
bind doing nothing when called without parameters 

### ISSUE THREAD

**Issue by veronicabend** [Foliotek/Croppie#124]
I am using croppie inside a jQuery Mobile popup.

I was using an older version ok, but when I replaced the files with current version, it would show the image very zoomed out when the popup was opened.

I tried several changes in my code to no avail. 

I finally looked into croppie source code, added some debug messages, and detected that _updatePropertiesFromImage() was returning right after being called when bind was called with no parameters, because of this:

        if (!isVisible || self.data.bound) {
            // if the croppie isn't visible or it doesn't need binding
            return;
        }

self.data.bound was always true in this case.

I changed that part of code to:

        if (!isVisible) {
            // if the croppie isn't visible or it doesn't need binding
            return;
        }

and this has solved my issue. I wanted to let you know.

**Comment by thedustinsmith** [comment]
Sorry for the delayed response.  Thanks for the info.  There were some known issues with `2.1.0` and calling bind without parameters.  They had been fixed in master for a while, but I never got around to making another release for bower and npm.

I made `2.1.1` this morning that contains fixes.  If you want, you can download it and see if it resolves your problems.
