### ISSUE TITLE
library loading (require/import)

### ISSUE THREAD

**Issue by alloyking** [Foliotek/Croppie#132]
The checking for existence of jQuery throws errors when requiring as a module:  
line 1038 "if (this.jQuery)".

Any reason not to do if (window.jQuery)?

**Comment by thedustinsmith** [comment]
Ah - good call.  I don't know why we would've done `this.jQuery` as opposed to `window.jQuery`.  I agree that it should be using `window`.

**Comment by marvinklein** [comment]
I'm having this same issue on a project in a RequireJS environment, so I've made a fix and submitted a pull request: https://github.com/Foliotek/Croppie/pull/135

**Comment by marvinklein** [comment]
There is still the problem that jQuery has to be loaded before Croppie, since window.jQuery is tested during module definition. There's really no good way to ensure that jQuery has been loaded, since it's not an explicit dependency in the module, and using a shim config with a module that is already a CommonJS module isn't a good idea according to their docs. Perhaps there should be a jQuery and non-jQuery build, or jQuery should be an explicit dependency in the define(..) call?

**Comment by thedustinsmith** [comment]
I'm not sold on adding a completely different build of croppie specifically for jquery.  That sounds like a lot of extra maintenance.  

I'm wondering if we can add jquery in the define(..) call and catch the error if it fails to load.  Anyone want to try that out?
