### ISSUE TITLE
zoomer.step should be '0.0001' instead of '0.1'

### ISSUE THREAD

**Issue by EricScottRichards** [Foliotek/Croppie#142]
My thinking behind this is that zoomer.min and zoomer.max both have 4 decimal places.  However, they only increment by 0.1, so the scale isn't all that variable.  If you change it to '0.0001', the zoom isn't any smoother when using the mouse scroll wheel, but it is smoother when using the zoomer to zoom in/out on the image.

**Comment by thedustinsmith** [comment]
Seems reasonable to me.  If you want to submit a PR, I'd be happy to merge it in.  Otherwise, I'll change it next time I have the project open.

**Comment by EricScottRichards** [comment]
Sweet.  I'll do it when I get off work. I'm loving Croppie, btw.  I just finished wrapping it up in an angular directive to use for a client.  I also made some local changes that add maxZoom and minZoom to the options for the project..  Not sure if you have any interest in seeing those changes as well.

**Comment by justcald** [comment]
+1

**Comment by thedustinsmith** [comment]
@EricScottRichards - thanks!  I'm seeing a lot of angular stuff related to croppie.  Can't say I have much experience with it, but it's fun to see.  Glad to hear it's working out for you.

Zoom options have been a problem since the get-go.  I'd be more than happy to see what you've done with them.  But if it's not too much trouble, could you put them in a separate PR?  

The zoom step is a definite change.  I'd hate for that one to get hung up on discussing the zoom stuff.  I kind of feel like we're just going to have to make a final decision on how the zoom api will work, but right now we're weighing our options.

**Comment by EricScottRichards** [comment]
yeah for sure.  sorry, but it probably won't be until tomorrow.

On Thu, May 26, 2016 at 5:52 PM, Dustin Smith <notifications@github.com>
wrote:

> @EricScottRichards <https://github.com/EricScottRichards> - thanks! I'm
> seeing a lot of angular stuff related to croppie. Can't say I have much
> experience with it, but it's fun to see. Glad to hear it's working out for
> you.
>
> Zoom options have been a problem since the get-go. I'd be more than happy
> to see what you've done with them. But if it's not too much trouble, could
> you put them in a separate PR?
>
> The zoom step is a definite change. I'd hate for that one to get hung up
> on discussing the zoom stuff. I kind of feel like we're just going to have
> to make a final decision on how the zoom api will work, but right now we're
> weighing our options.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Foliotek/Croppie/issues/142#issuecomment-222026589>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKRF_60fok1ZoTYWwAIU9Sg8Y4zFhodxks5qFjJHgaJpZM4In50O>
> .
>



-- 
Eric Richards
801.615.9902
