### ISSUE TITLE
Need to crop zoom out images , but results in irregular shapes and blured image

### ISSUE THREAD

**Issue by Vignesh-adc** [Foliotek/Croppie#143]
Hi,

Can u please check 1.png , this is what i want to crop
but it results as 2.png , can u check that 
Please reply as soon as possible

Thanks,
Vignesh.D
![1](https://cloud.githubusercontent.com/assets/19604797/15600964/e62fa59c-240a-11e6-934a-23355ec92e48.png)
![2](https://cloud.githubusercontent.com/assets/19604797/15600969/f086f748-240a-11e6-925d-ccef6ec49711.png)

**Comment by thedustinsmith** [comment]
The more information you can provide, the better.  Are you able to share the code you're using to display that?  To be honest, the ability to zoom an image smaller than the viewport was a feature we just implemented, and didn't really test a whole lot because we don't use it.  But without any dimensions or anything to go off of, I can't really speculate on what your problem might be.
