### ISSUE TITLE
enforceBoundary producing blank images with Safari (desktop / iOS)

### ISSUE THREAD

**Issue by sonnybaker** [Foliotek/Croppie#163]
Hello,

First off, thanks for your work on Croppie - it's a superb tool, really great work.

However, we've run into a hitch when setting `enforceBoundary` to false. In Safari, if the image is smaller than the viewport, the resulting canvas data is completely blank. This happens on both desktop and mobile versions of the browser. Chrome and Firefox work perfectly fine. I know `enforceBoundary` was only recently introduced and is somewhat of an experimental feature, but if you're able to shed any light on exactly what's causing this bug it would be greatly appreciated.

Thanks!

**Comment by thedustinsmith** [comment]
@sonnybaker Thanks for the very thorough explanation.  I'm definitely seeing the same problem.  At the moment, I don't have any additional information for you, but I'm looking into it.

**Comment by thedustinsmith** [comment]
At first I thought this may be because we're sending negative numbers to `CanvasContext.drawImage()`, and maybe safari doesn't like that.  After more research, that doesn't appear to be the case, I'm not sure exactly what's going on, but I can't get safari's canvas to like anything I'm doing when it comes to adding blank space around that image.

Here's a jsbin I've been tinkering in: https://output.jsbin.com/qoloba

`ctx` is what croppie is currently executing when zooming out beyond the boundaries of the image.

`ctx2` is my attempt to try to avoid negative numbers.  Ignoring the fact that I have no idea how I'd even get those new `dX, dY` values.

If anyone has any insight on this one, I'd love to hear it.  After a couple hours of research, I'm tempted to submit this as a webkit bug for not accepting negative values in the sourceX and sourceY parameters.  But I wouldn't be surprised it they just don't allow that.  Not to mention that replacing the negative values doesn't even fix the problem.

**Comment by nguyenphuc** [comment]
This occurs also with Internet explorer 11.

**Comment by sonnybaker** [comment]
@thedustinsmith just came across this, could it be the same issue? http://stackoverflow.com/questions/35500999/cropping-with-drawimage-not-working-in-safari

**Comment by ninnemannk** [comment]
@thedustinsmith - I'm running into what I believe is the same issue but slightly variated. 

In Safari (mobile or desktop) with enforceBoundary and showZoomer both set to true:

- Upload an image
- Use Zoomer to zoom all of the way out
- Call croppie.results

Results in a blank image. Strangely enough, if I change the format option passed to results() to a 'jpeg' it results in a completely black image. I will continue debugging, but I hope this helps.

**Comment by ninnemannk** [comment]
@sonnybaker - good stuff! You were on the right trail. After lots of debugging, I realized that while calculating the width and height Croppie is for some reason adding 1px to both the width and height.

`           
croppie.js - Line 947, 948

        width = (points[2] - points[0]),
        height = (points[3] - points[1]),
`

As a temporary work around I simply modified the width and height by adding: 

`
croppie.js - Line 955

        if(width > this.elements.preview.width){
            width = this.elements.preview.width;
        }
        
        if(height > this.elements.preview.height){
            height = this.elements.preview.height;
        }
`

The reason for this is because the provided sourceHeight and sourceWidth are greater than the actual width of the image itself. In all other browsers the canvas seems to compensate for that. Unfortunately Safari does not currently.

**Comment by thedustinsmith** [comment]
I'm guessing the 1px is the border of the viewport.  That's been pointed out in a couple issues.  Thanks for the additional info.  That seems like a reasonable change.  

Though I don't see the need for the `enforceBoundary: false` option myself, I wonder if this would negatively affect that?  For example, if I zoom out the image so I have 20px of white space between it and the image edges, does the result still have that equal gap of white space?

Honestly, I don't use `enforceBoundary: false` enough to even know if that's how it currently works, but it's the only scenario that sticks out to me.  Guess I need to throw a better enforceBoundary demo on the home page. :\

**Comment by sonnybaker** [comment]
Unfortunately even when applying @ninnemannk's fix, Safari's `drawImage` still doesn't seem to like images that are cropped smaller than the viewport, I suspect because the sH/sW will always need to be greater than the width and height if we need blank space around the image. It looks like #153 got close to a solution, though I actually get the same blank result in Safari when running the code from that Pastebin.

**Comment by ninnemannk** [comment]
@sonnybaker , @thedustinsmith - I apologize, I should have specified.. My issue was slightly variated from `enforceBoundary: false` issue. 

In my implementation I was using `enforceBoundary: true` and `showZoomer=true`. While zooming ALL the way out with the zoomer, the same blank image was the result. After ensuring that the sWidth and sHeight was not greater than the image source itself, my issue was fixed. 

I will be glad to lend a hand and try looking for a solution to `enforceBoundary: false`. The issue may pertain to the second part of Kaiido's explanation of the Safari bug: 

> you even have to check that your source X (2nd param) and source Y (3rd param) added to the source width and source height won't make it try to draw non-existent pixels. – Kaiido

**Comment by thedustinsmith** [comment]
I finally found a fix for this.  #219 is having the same problem.

Instead of passing negative values for the `sx, sy` values of `drawImage`, I'm adjusting the `dx, dy` values.

I'll throw these changes in 2.4.0, but I'd be thankful if you two would test it out for me.

**Comment by thedustinsmith** [comment]
I'm assuming 2.4.0 fixes this, so I'm going to close this since I can't easily use safari right now.  If it's still an issue with safari in 2.4.0, just comment on this case and I'll reopen it.

**Comment by bellsenawat** [comment]
Sorry, I got this problems on Safari when using enforceBoundary 

then I update js file and change to using rawcanvas

I test many times the result of image position is not the same crop modal. 

![screen shot 2016-12-07 at 2 01 26 pm](https://cloud.githubusercontent.com/assets/5281760/20958032/e944424c-bc85-11e6-842a-49345c01dc6b.png)

as an attached this is what I see when I cropping, after that the return result just show me only blank image but...... if I move image to left of boundary

![screen shot 2016-12-07 at 2 05 53 pm](https://cloud.githubusercontent.com/assets/5281760/20958093/606b0752-bc86-11e6-9648-c9c20614066d.png)
 

this is result 

![2](https://cloud.githubusercontent.com/assets/5281760/20958109/79d1654c-bc86-11e6-85aa-2785e10b0344.png)

**Comment by oscarhandsome** [comment]
Hello, @thedustinsmith thank you for your tool!

I have issues with `enforceBoundary: false`
Your fixes in the Version: 2.3.0 is available in the Version: 2.6.2? Because in the new version some functions look bigger.
