### ISSUE TITLE
Allow User Adjustable Viewport Size

### ISSUE THREAD

**Issue by own3mall** [Foliotek/Croppie#171]
Can the user adjust the viewport size themselves (by dragging the viewport edges) when using Croppie?  Do we have to provide a fixed value like so:

```
croppieInstance = $('.conainer', $('div.e')).croppie({
    url: src + '?' + d.getTime(),
    enableOrientation: true,
    boundary: { width: 600, height: 450},
    viewport: { width: 400, height: 300, type: 'square' },
});
```

I have the zoom feature enabled, but there are many times when I as a user want to adjust the viewport area myself by enlarging or decreasing the edges of the crop area.  Is this possible?

**Comment by thedustinsmith** [comment]
Nope.  It's not possible.  Although I'll keep this issue open because I can see this being useful.

**Comment by fdanielsen** [comment]
We are also interested in something like this, although one would have to be able to constrain which dimension can be adjusted (eg. locking width, but let height be adjustable). In this case for us the boundary size would be updated proportionally.

We will be putting some effort into getting this feature implemented in Croppie itself rather than find a way around it, hopefully it'll be interesting to maintainers to merge into core once done.
