### ISSUE TITLE
PNG Viewport Cuts Off Part of the Image when Zoom is All the Way Out

### ISSUE THREAD

**Issue by own3mall** [Foliotek/Croppie#172]
When using the below code with a png image:

```
croppieInstance = $('.conainer', $('div.e')).croppie({
    url: src + '?' + d.getTime(),
    enableOrientation: true,
    boundary: { width: 600, height: 450},
    viewport: { width: 400, height: 300, type: 'square' },
});
```
Croppie's viewport is cutting off part of the image when zoomed all the way out as shown in the attached screenshot.  The dimensions of the image originally were 1600 x 1600.

![cutoff_croppie_viewport](https://cloud.githubusercontent.com/assets/11792538/17086314/c90e7f82-51ab-11e6-8231-0fb77a74ab53.jpg)

**Comment by thedustinsmith** [comment]
This is due to your image not being the same dimensions as your viewport.  You're zoomed all the way out because you've reached the minimum width.  

You can use the `enforceBoundary` initialization parameter if you'd like.  I can see why there might be the need for a parameter that indicates which dimension should be enforced - width/height.  But for right now, that doesn't exist.

**Comment by thedustinsmith** [comment]
Closing but adding a new feature for the enforce boundary adjustments: #207
