### ISSUE TITLE
The canvas result should generate the correct canvas dimensions

### ISSUE THREAD

**Issue by nicosiamike** [Foliotek/Croppie#20]
Generating a result via canvas creates a data/image which correctly contains the viewport selected, however, the actual image dimensions do not match.  Could the created canvas have the same dimensions as the viewport?  This would eliminate the need for re-sizing.

**Comment by thedustinsmith** [comment]
I can see the need for specifying the result size when the result is of `canvas` type.  However, I think the default behavior should be to return the viewport at the native size of the image.  

At first I was thinking we could pass a type, width, height into the result method.  But I'm not sure the width and height make sense, since we probably want to maintain the aspect ratio of the cropped image.  Maybe the result method could take in an object like so:

```
{
type: 'html|canvas', // default canvas
size: 'original|viewport' //default original
}
```

Would this solve your problem @nicosiamike ?
