### ISSUE TITLE
Download Image Naming Convention 

### ISSUE THREAD

**Issue by ziankabir** [Foliotek/Croppie#231]
I want to download the cropped image using a download button. I've done that already but the problem is with the file name. I want that what is my filename will be the file name as I've uploaded and download the cropped image. Please visit the following link: 
[http://nazrulkabir.com/imagecrop/]

**Comment by thedustinsmith** [comment]
Just capture the file name on the filereader change event, and save the file name.
```
reader.onload = function (e) { 
  console.log(e); // the file name should be in here somewhere; Save it into a variable
  //...
};
```

Then instead of saying `<a download="dataurl" />` ... do `<a download="originalfile.ext" href="dataurl" />`.

This isn't really an issue with croppie.  Next time try stackoverflow.com - you'll get help a lot quicker on that site or similar sites than through this repo.

**Comment by ziankabir** [comment]
Thanks for the reply!
