### ISSUE TITLE
Issue with upload image size restriction and in IE cropping is not working

### ISSUE THREAD

**Issue by Nagarjungowda** [Foliotek/Croppie#262]
Hi i am unable to restrict image upload size and in internet explorer 11 cropping is not working? please suggest a way to fix these issues.

**Comment by thedustinsmith** [comment]
I'm not quite sure what issues you're having.  But if you're trying to restrict the size of the file they can select when uploading a file maybe try this post: http://stackoverflow.com/questions/5697605/limit-the-size-of-an-file-upload-html-input/17173301#17173301

If you can come up with a more detailed description of what issues you're having I can reopen this case, but since I've taken a very long time to respond, and the problem isn't well documented, I'm going to clsoe this one.
