### ISSUE TITLE
Only slider

### ISSUE THREAD

**Issue by darkthefirst** [Foliotek/Croppie#264]
The image just display: none

**Comment by aveeshkumar** [comment]
After adding the JS and CSS - via CDN or locally from server and attaching to IMG element - I only get slider and the image croppie is attached to "disappears" - only the slider remains visible

The demos and examples work but hey ar eloading a whole lot of other CSS and JS....

will appreciate an answer - thanks

**Comment by thedustinsmith** [comment]
If either of you can put together a jsbin or jsfiddle demonstrating the issue, we can help.  Otherwise, I'm having a hard time understanding the problem.

**Comment by aveeshkumar** [comment]
Hello,

Thx for getting back - I put it on my website 

http://www.openschoolsite.com/croppie.html 

http://www.openschoolsite.com/xcroppie.html - without croppie

**Comment by thedustinsmith** [comment]
Please try the following - see what works:
* Get rid of the width and height attributes on your image
* Specify `viewport` and `boundary` dimensions when initializing croppie

Those two things seem to fix it for me on your website.  If it's the width and height on the image, I don't think there's a bug here.  The only thing I can think to do would be to remove those attributes from any image that croppie is initialized on.

If it's the viewport and boundary not being specified, I can see a fix being needed.  Although I would think more times than not, we'd be specifying those dimensions rather than using the defaults.

**Comment by aveeshkumar** [comment]
Thank you - Thank you !!

I really appreciate it - coming from PHP with close to Zero JS - I get very frustrated - but help from wonderful folk like yourself prevent me from giving up!

Yours is a wonderful lib - If I can ever get crop/upload to work - will definitely ping you back once in production at a small school!

**Comment by kushanz** [comment]
> Hello,
> 
> Thx for getting back - I put it on my website
> 
> http://www.openschoolsite.com/croppie.html
> 
> http://www.openschoolsite.com/xcroppie.html - without croppie

It Works For me. Thanks
