### ISSUE TITLE
Very small image 

### ISSUE THREAD

**Issue by karmis** [Foliotek/Croppie#28]
Very small image in case of el.croppie ('bind', src) where src is uri.
Look on a screenshot.

![Screen](http://dl3.joxi.net/drive/0004/1376/279904/151210/ad6ea4e1dd.jpg)

I decided adding of the minimum value for zoomer

```javascript
        wrap.classList.add ('cr-slider-wrap');
        zoomer.type = 'range';
        zoomer.classList.add ('cr-slider');
        zoomer.step = '0.01';
        zoomer.min = 0.5;
        zoomer.value = 1;
```

Forgive me for my English

**Comment by thedustinsmith** [comment]
If you look in `_updatePropertiesFromImage` we set the zoomer's min and max based on the image's dimensions relative to the viewport's dimensions.  It doesn't look like it's working in your case for whatever reason.  

Are you binding any points?

I did add some logic that tries to center the image in the viewport if no points are provided, because I did notice some odd behavior with smaller images.  It's possible that logic might help with your issue.  If you install `1.0.3` do you still have the issue?

**Comment by thedustinsmith** [comment]
Woops - wrong issue.

**Comment by thedustinsmith** [comment]
I'm going to say this one is fixed until we hear otherwise.
