### ISSUE TITLE
Getting Initial Zoom Value

### ISSUE THREAD

**Issue by MentalGear** [Foliotek/Croppie#289]
I'm rolling my own slider, and to set the starting value of the slider correctly to the zoom size of the image, I need to find out what the initial zoom level of croppie is. However, that information doesn't seem available via the API ( neither any min / max zoom levels ).

**Comment by buccolo** [comment]
I've just done something similar @MentalGear.

When `croppie` loads, it will call the update function. In that callback, you'll have access to `this.croppie.elements.zoomer`. This is the element that contains the zoom input, you can then check the `zoomer.max` and `zoomer.min` values.

**Comment by thedustinsmith** [comment]
Way too late to the party, but just for further questions ... another way to accomplish this would be to call `get()` in the `bind()` callback. 

But if you want min/max values, @buccolo 's answer would be the only way to get that.

I'm going to close this one since you guys seem to have figured it out yourselves.  Thanks for helping out!
