### ISSUE TITLE
Get the URL of the original image

### ISSUE THREAD

**Issue by NeeONCorp** [Foliotek/Croppie#299]
Tell me how to get the address of the original image?

**Comment by garek007** [comment]
What do you mean address? If you drag an image from your desktop it doesn't have a URL.

**Comment by rob-lindman** [comment]
I think this is straightforward and it would be useful. a getURL method would return the URL of the image which is loaded in the croppie. Once an image is loaded, there doesn't seem to be any way to retrieve this. I load croppie code separately and then set the url with data from an ajax call. In an issue I just posted, it would be convenient to get the URL of the image that was sent to croppie, instead of having to have a global variable for it.
