### ISSUE TITLE
Get returns wrong initial zoom

### ISSUE THREAD

**Issue by riteshzefo** [Foliotek/Croppie#308]
I am trying to get the coordinates and zoom of the image. The **get** returns the actual coordinates but returns a **zoom of 0.1781 whenever the image hasn't been zoomed in or out at all.**

I have tried explicitly setting the points to the width and height of the image but all in vain. Please let me know in case something is wrong in the code.
     
                   var url = $(this).attr('src');
                    var points = [0, 0, $(this).width(), $(this).height()];
                    var basic = $('#croppie-container').croppie({
                        viewport: { width: 600, height: 450 },
                        boundary: { width: 650, height: 500 },
                        showZoomer: false,
                        points: points
                    });

                    $('#croppie-container').croppie("bind", {                          
                        url: url,
                    });

                    var croppie_details = basic.croppie('get');

**Comment by riteshzefo** [comment]
@thedustinsmith

**Comment by thedustinsmith** [comment]
Couple things:

1) I'm guessing you want zoom to be 1 or 0 for initial zoom since the user hasn't changed anything?  That's not the case.  As seen in this line https://github.com/Foliotek/Croppie/blob/master/croppie.js#L859, initial zoom is automatically calculated based on several factors.

2) `bind` doesn't happen immediately.  It returns a promise, try waiting for that promise to finish, then getting the zoom value

**Comment by syosoft** [comment]
https://github.com/Foliotek/Croppie/issues/47
