### ISSUE TITLE
Some images shift to the left when uploaded - not centred.

### ISSUE THREAD

**Issue by thatandyrose** [Foliotek/Croppie#327]
This is an easy one to recreate you'll be happy to hear! :-)

So, I found this only happens with some images, particularly images taken with the iPhone camera.

Here's a couple:

https://www.dropbox.com/s/2exebs9ticdewe3/Speaker.jpeg?dl=1
https://www.dropbox.com/s/ckxfs89978pk6yg/IMG_2111.JPG?dl=1

Now, go to your homepage:

https://foliotek.github.io/Croppie/

Then, go down to the upload/exifjs demo, the first demo with the upload button.

<img width="1373" alt="screen shot 2017-05-26 at 16 22 21" src="https://cloud.githubusercontent.com/assets/778074/26502292/35018fb2-4234-11e7-8eb9-fc7b407d3d0c.png">

Now upload either of those images. You'll see they upload but show shifted to the left, not centred.

Here's an image I grabbed from google. Notice it doesn't happen with this image:

https://www.dropbox.com/s/0r93a8m07e4juky/long.jpg?dl=1

Any ideas?

**Comment by thatandyrose** [comment]
Just a couple of updates.

1. Here's what it looks like when it goes wrong:

<img width="962" alt="screen shot 2017-05-26 at 17 32 53" src="https://cloud.githubusercontent.com/assets/778074/26503645/74a984e4-4239-11e7-9550-38b7ce30f695.png">

2. Note that when I downgraded to 2.4.0 it works again :-)

So something in 2.4.0 => 2.4.1 broke it.

**Comment by thedustinsmith** [comment]
Sorry for the delay, but I finally found the issue.  Thanks for the detailed submission, it really helped.

In 2.4.1 someone added something to center the image on binding.  This used the img's width and height.  With mobile oriented images, those dimensions got mixed up in certain circumstances.  I've added a helper method to get the correct dimensions.

This should be fixed with the next release.
