### ISSUE TITLE
Image cut after rotation and vertical alignment

### ISSUE THREAD

**Issue by antoinelorcy** [Foliotek/Croppie#349]
Hello,
In the doc page : http://foliotek.github.io/Croppie/#documentation

![capture d ecran 2017-07-13 a 14 18 25](https://user-images.githubusercontent.com/1907309/28166046-b7257bb2-67d6-11e7-916f-42248e715717.png)

the exemple with the dog picture fail when we rotate left/right and drag down :
![capture d ecran 2017-07-13 a 14 18 39](https://user-images.githubusercontent.com/1907309/28166056-c01278f6-67d6-11e7-8a77-e4c2d56af992.png)

Result image is not complete :
![capture d ecran 2017-07-13 a 14 18 51](https://user-images.githubusercontent.com/1907309/28166078-d6826b3c-67d6-11e7-94dd-8ba593907c2d.png)

the merged #326 doesn't fix this.

**Comment by tinque** [comment]
+1

**Comment by avrelaun** [comment]
+1

**Comment by thedustinsmith** [comment]
Closing this in favor of #293 since it's older.

Couple things to add: 
1) I can't get this to happen.  And #293 has lost steam, which leads me to believe this is resolved.
2) +1's are a thing of the past.  Github added reactions to alleviate this.  If you want to +1 in the future, just give the issue a thumbs up.
