### ISSUE TITLE
Feature request: Accept Canvas in bind() to allow for custom modifications

### ISSUE THREAD

**Issue by rafasashi** [Foliotek/Croppie#394]
I am using Croppie to generate background images and I would like to add overlay and transparency editors in addition to the zoomer feature.

Could we work on this together or would you please just put me on the right path to develop that feature as a plugin?

**Comment by thedustinsmith** [comment]
Sorry - I know this is far delayed.  But your issue made me think of an idea.

Currently in the `_bind()` method we're expecting a url.  In order to make this more expandable, maybe it would be a good idea to change that method to allow a canvas object. 

This would give anyone the ability to modify their canvas object, in addition to croppie resizing/rotating/cropping.

In your case, you could add your overlay to your canvas, modify the transparency, then bind it to croppie.  Croppie and your code could both use the same canvas and you could both modify it to your heart's desire.

If you'd like to work on this, I'd love the help, if not, maybe this is a 3.0.0 feature, MAYBE.  I have to find more time to work on Croppie before that's going to happen.

In the meantime, I'm going to hijack your case title, because I think this idea has legs.

**Comment by rafasashi** [comment]
Hi Dustin,

Thanks for your reply.

Allowing  a canvas object in _bind() method sounds a really efficient and
flexible to extend Croppie's functionalities and custom features.

I would like to help you on that, let me know when you have time to work on
this with me.

Regards,
Raphael

Raphaël

2017-12-08 20:28 GMT+05:45 Dustin Smith <notifications@github.com>:

**Comment by winternet-studio** [comment]
I have a situation where I have TIFF images which are converted to <canvas> elements in order to work in Chrome and Firefox, so letting me bind that element instead of a URL would also be very beneficient to me.

**Comment by TadVab** [comment]
any update on this? i too would like to put what's on a canvas into croppie. thanks

**Comment by rafasashi** [comment]
I think the answer is to set the result type to 'rawcanvas'.

According to the doc 'rawcanvas' returns the canvas element allowing you to manipulate prior to getting the resulted image.
