### ISSUE TITLE
How to set default zoom size on load programatically

### ISSUE THREAD

**Issue by chandraa06** [Foliotek/Croppie#40]
i want to give default zoom value at the time of initializing or after initialization ?

could you help me with that.?

**Comment by thedustinsmith** [comment]
Currently it's not possible through the API.  You could manually set the value of the slider and trigger a change, and that should work.

However, I've always thought this would be a good feature to have.  I'm just not sure on the implementation of it.  It's tough adding a `zoom` option to `bind()` since we don't know the min and max zoom until we determine the size of the image.

Any suggestions for an implementation?

**Comment by chandraa06** [comment]
Already I'm setting currenzoom value to 0.6 like that. But it doesn't
changing

**Comment by thedustinsmith** [comment]
I'd have to see some code to offer useful advice.  Are you triggering a change on the slider?

**Comment by chandraa06** [comment]
function _initializeZoom() {
        var self = this,
            wrap = self.elements.zoomerWrap = document.createElement('div'),
            zoomer = self.elements.zoomer = document.createElement('input'),
            origin,
            viewportRect,
            transform;

        wrap.classList.add('cr-slider-wrap');
        zoomer.type = 'range';
        zoomer.classList.add('cr-slider');
        zoomer.step = '0.01';
        zoomer.value = 1;

        self.element.appendChild(wrap);
        wrap.appendChild(zoomer);

self._currentZoom = 0.6;
        change();
        
        ////chandra additional code wrote here this line
        
        //_setZoomerVal.call(self, 0);
        ////chandra additional code wrote here ends this line

**Comment by thedustinsmith** [comment]
I suspect it's because you're passing 0 as a parameter into that function.  What are you trying to accomplish by setting the zoom to zero?

**Comment by chandraa06** [comment]
Ya, that's what I'm trying in that function, could you help me with that?

**Comment by thedustinsmith** [comment]
Why are you passing `0` into that function?

**Comment by chandraa06** [comment]
Bcz you set zoom step as a0.01 and zoom value= 1, so I thought your using 0
to 1 as zoom range

**Comment by thedustinsmith** [comment]
We set zoom range based on the width of the image you bind and the width of your viewport.  Regardless of that, setting zoom to `0` is never going to work.  Since the scale of the image could never be `0`, unless you didn't want the image to be visible.

Check out [line 643](https://github.com/Foliotek/Croppie/blob/master/croppie.js#L643), that's where we're setting the min and the max zooms.

**Comment by thedustinsmith** [comment]
I added a `setZoom(value)` method.  This should allow you to do what you want to do.  Thanks for the submission.

**Comment by maxvaser** [comment]
@thedustinsmith  - Very cool and useful library!! 

It looks like the setZoom function is throwing an error when called. Using version 2.0.1. 
just tried to add the		uploadCrop.setZoom(0);    or    uploadCrop.setZoom(1);
after the bind default image call. I would like a default image to be the viewport size. uploadCrop is my Croppie instance. 
firebug:  Error: TypeError: uploadCrop.setZoom is not a function

Thanks!

**Comment by thedustinsmith** [comment]
@maxvaser - Thanks!

How'd you install croppie?  By just downloading the files from github?  I'm not very good about keeping master in check by minifying and testing.

Is your `uploadCrop` a jquery cropper?  If so you need to call `uploadCrop.croppie('setZoom', val)`

**Comment by maxvaser** [comment]
@thedustinsmith  thanks! I am using the Jquery methods. That's it, no errors. I was apparently using the example that's for the vanilla.  
If I set the value to zero it still sets the default image to the boundary box and not the smaller viewport size. I was thinking zero would set it to viewport since if you were showing the existing image for a profile pic then it's zoomed in a bit and pixelated. If that's not the intention of setZoom. Then maybe a setting to set the initial slider value to zero would do the trick. I didn't see a method for that. Does it exist? 

I pulled it in using NPM, which I think just pulls directly from github version you have set in the package.json file.

Thanks again!

**Comment by thedustinsmith** [comment]
There's a bit of confusion with setZoom.  Seems like most people, like you, believe the value passed in should be in relative to the size of the image relative to the boundary.  Whereas I'm just setting the zoom to `value * the native size of the image`.  Obviously, I need to give this one some thought.

**Comment by GaganTiwari** [comment]
@thedustinsmith i m not able to fix it can u plz any other solution.

You can add you here in my site. http://www.askmedeveloper.com/

Thanks in advance.
