### ISSUE TITLE
Can't style zoom slider with js

### ISSUE THREAD

**Issue by k-lusine** [Foliotek/Croppie#41]
Hi, thanks for the plugin

I'm facing an issue at the moment. I need to style the zoom slider with js as default css doesn't work in my case (i need a different color for the filled part of the range, but i can't achieve it in webkit browsers with the help of css).

I tried two different plugins for styling range input with jquery and none of them worked. The slider is generated, but real range value isn't changed, and as a result the image isn't zoomed in/out. But the plugins work okay with an ordinary input(if you make the real input visible, you can see it)
see fiddle here (now it uses rangleslider.js but I tried formstone as well, the same result)
https://jsfiddle.net/ohn1xbn1/7/
 I also tried to call rangeslider after image change
https://jsfiddle.net/ohn1xbn1/8/
and also with setTimeout
none of them works

What can I do

Regards
Lusine

**Comment by thedustinsmith** [comment]
I haven't tried it personally, but you might try using [this implementation of rangeSlider](https://github.com/Stryzhevskyi/rangeSlider) that's not using jQuery.  The problem is rangeSlider is triggering a change with jQuery, and to the best of my knowledge jquery events and native events aren't compatible.

Otherwise, I'm thinking eventually we're going to add a `setZoom(v)` method on croppie, so that might solve your problem.

**Comment by k-lusine** [comment]
Thanks, I'll try this way too though  I already managed to style only webkit range with js. 
Yes setZoom will be very useful, 
Thanks

**Comment by vandensudarsono** [comment]
so, was this solved by setZoom method ?
