### ISSUE TITLE
Incorrect crop region returned base64

### ISSUE THREAD

**Issue by thibaultvanluchene** [Foliotek/Croppie#415]
In the video you can see what's going wrong (first crop goes well, second and third fail (and probably all coming after those)):
https://youtu.be/4V7P_iBLgpA

Is there something which needs to be reset between the uploads or is this an issue?

When closing the modal I call destroy(), which fixed some issues I encountered earlier. But it's my goal to let people upload several pictures in one run without having to close the modal.

**Comment by lightframes** [comment]
I have the same problem. When it goes over a certain zoom it calculate wrong and the crop is not correct.

**Comment by RGravesDev** [comment]
There are two different problems here. The first one that thibaultvanluchene has can also be seen on the demo site http://foliotek.github.io/Croppie/  in the example "Upload Example (with exif orientation compatability)".  The first time you upload an image it works, but each additional time it fails, until you refresh the browser. 

In the upload function you call on the page to uplad a file, for example uploadPhoto(event) { }  the event has srcElement. Try setting event.srcElement.value = '' when closing the modal. This will make sure the image src is cleared out from the browser for the next time to start from null, because the browser keeps this in memory. Hopefully this will work. 

As for lightframes problem with the zoom calculations, I had the same problem. High-resolution images that we uploaded were cropped way off-center from what it looked like in the zoom circle. It turned out to be a max-width:100% style on the img tag for the modal where the cropper was being used. The style on the modal img tag was affecting the cropper zooming functionality from working correctly!

**Comment by thedustinsmith** [comment]
Hm .... thanks for the notes @RGravesDev .

It may be worth thinking about adding a style `max-width: none !important;` in croppie.  As much as it makes me cringe.

Related to the upload example, unfortunately it's a known bug ... being worked on when I can find time.
#352 

I'm going to close this issue in preference of that one since it has the most attention right now, but I'll take note of your suggestions ... they'll certainly help.

**Comment by RGravesDev** [comment]
Hey Dustin,

Glad I could help. My suggestion is if you are going to add the max-width
css, you should probably also add max-height: none !important;  at the same
time just to cover another use case.

In playing around with it some more, I found that when I used enableExif:
true, it solved a few problems. First of all, the image tag went away in
the DOM and instead it's using a canvas tag. Then the above css fix was not
needed. Also it solved a problem I had when I cropped a small image. I save
the cropped image at 240 x 240, but any image I uploaded into Croppie
smaller than those measurements was saved off-center even though the small
image was centered and looked good in the croppie before saving. Also on
mobile, the image in portrait was saved in landscape. When I used
enableExif: true, and added the exif.js library, everything worked
perfectly! I didn't need the css, I could upload small images, and they
were upright on a mobile device. I now have a happy QA department.

Just thought you would be interested to know.

thanks,
Russell
