### ISSUE TITLE
Getting CORS origin problem.

### ISSUE THREAD

**Issue by akashanand708** [Foliotek/Croppie#429]
I am getting the below error while accessing the image content from other server.
even the crossorigin is set to "anonymous".
<img width="1390" alt="screen shot 2017-11-27 at 8 33 37 pm" src="https://user-images.githubusercontent.com/6744343/33273183-8ab89396-d3b2-11e7-9bda-0ce7dd1bd241.png">

<img width="679" alt="screen shot 2017-11-27 at 8 33 20 pm" src="https://user-images.githubusercontent.com/6744343/33273207-9ac2b8c0-d3b2-11e7-95b8-713374359499.png">

**Comment by thedustinsmith** [comment]
Do you have control of https://sporkapp1.imgix.net?

Not only does the image need to have `crossOrigin=Anonymous` but the server has to return the right headers.  You should see `Access-Control-Allow-Origin:[* or your domain]` in your headers if you inspect chrome's network panel.  

I'm closing this issue, because this isn't related to croppie and I have a lot of issues to shuffle through.  Feel free to comment if you need more help.
