### ISSUE TITLE
croppie seems to be incompatible with vue.js

### ISSUE THREAD

**Issue by yennor** [Foliotek/Croppie#517]
## Expected Behavior
When using vue.js and croppie together, croppie should be working

## Actual Behavior
Croppie doesn't work properly.
The zoom slider and the frame which would include the image gets created and shown. But inside the frame only "preview" is written, and nothing else happens. Only when I disable vue.js croppie works.
I've tried out vue-croppie now, and like that it seems to work (but cost me some hours to find that out).

## Steps to Reproduce the Problem

  1. include vue.js and croppie.js
  1. instantiate vue.js
  1. instantiate croppie.js

**Comment by thedustinsmith** [comment]
If you could setup a github repo to demonstrate the issue, I can try to look into it.  But I don't have any experience with vue.js, unfortunately.  And I have way too much on my plate to dig into it now.  Otherwise, I would suggest just using vue-croppie.

**Comment by yennor** [comment]
unfortunately I don't have my previous setup anymore since I went with vue-croppie... And I don't have time myself to redo the setup :-(
But at least like that here, people are already warned (if they look for the same issue).

**Comment by thedustinsmith** [comment]
Alright.  I'll close this one then.  

For the record, vue-croppie is listed in the README.

**Comment by bacanu** [comment]
For me the problem occurs when:
1. I include croppie.js (the regular, non-vue version)
2. I include vue.js
3. the croppie element is inside the vue app element.

Because the croppie element is inside the vue app element, it's a similar issue to what happens if you include croppie in a modal/popup. 

How I fixed it: Vue has a lifecycle hook: `mounted` and inside the mounted callback it's where i put the croppie initialization code.
So now vue renders the elements and after the elements are rendered, the croppie element is visible and it can initialize as expected.
