### ISSUE TITLE
Croppie fails to fit landscape images

### ISSUE THREAD

**Issue by Carmezim** [Foliotek/Croppie#549]
## Expected Behavior
Image is properly bounded in viewport

## Actual Behavior
Landscape image is bind to Croppie with a blank area underneath and only properly 
set the image boundaries when an update even is fired e.g. zoom is changed, bounding box is resized etc.

## Steps to Reproduce the Problem

  1. Bind landscape image
  2. Do anything on croppie and image which then had a blank/empty area will fit properly

  
## Example Link
![image](https://user-images.githubusercontent.com/16518410/42830988-21e81dae-89bb-11e8-88d4-63793b6ec4c2.png)
![image](https://user-images.githubusercontent.com/16518410/42831000-2ac8516e-89bb-11e8-8374-45146033308a.png)

* Link:

## Specifications

  - Browser: Google Chrome
  - Version: Latest

**Comment by thedustinsmith** [comment]
Please include a jsbin/jsfiddle or any kind of code.  It's hard to suggest fixes without knowing what your code is doing.

**Comment by thedustinsmith** [comment]
I think instead of adding the width and height of the img, you actually want to add the width and height of the viewport.  Although I'm not entirely sure what you're trying to gain by passing points.

So, a more accurate description of what's happening here is that if invalid points are passed in, croppie still accepts them and processes them, when perhaps it shouldn't.

**Comment by Carmezim** [comment]
I'm passing points to have a specific bounding box when I bind the image, that's what the `points` parameter is for, correct?

The `width` and `height` are just values returned from the API that I can use to calculate `[topLeftX, topLeftY, bottomRightX, bottomRightY]` which is exactly what the `points` array is at the end.

**Comment by thedustinsmith** [comment]
You're right about the points.  Although it can be used to pre-place the image, my original intention was these points could be used with certain cropping plugins, if someone wanted to use something besides html/js abilities (say imagemagick for example).  One distinguishing factor `bottomRightX` and `bottomRightY` are where the bottom right corner of the viewport should land on the image.  

Let's say your image is 800px in width and 400px in height, and your viewport is 400x400.

So you want croppie to align `0, 0` of the image to the top left of the image, which is what croppie's doing.  Then you want the bottom right of the view port to be at the `x,y` of `800,400`.  Croppie's doing it's best, it's placing the right side of the viewport on the 800 edge, but it can't do the 400 after that because it would skew the image.  Does that make sense?

When I said I'm not entirely sure what you're trying to gain by passing in points, I mean I don't know what you're trying to gain by passing in the top left of the image, and the bottom right of the image.  What behavior are you looking for that doesn't already occur when you don't pass in the points?

**Comment by Carmezim** [comment]
Hi @thedustinsmith, I've made some changes in my code and got it working. Thank you for your help and for the great tool!
