### ISSUE TITLE
Remove jQuery dependency possible?

### ISSUE THREAD

**Issue by ti** [Foliotek/Croppie#579]
## Remove jQuery Dependency?

in most of case, we should upload a file by "FileReader" before use Croppie, and the FileReader is IE 10+ feature, so we do not need the jQuery in modern html5 browser ?

so, Is it possible to use Croppie without jQuery? what is the difficult about it?

**Comment by thedustinsmith** [comment]
Nothing difficult about it at all - the demos section contains a "vanilla example" that doesn't use jquery:
http://foliotek.github.io/Croppie/#demos

**Comment by ti** [comment]
Thanks, it is really help me,  but i still have some problem when i use [zeptojs](https://zeptojs.com/) (alternative about jQuery), because the `$` and `window.jQuery` sign, this library not compatible with  zeptojs.

###  so, if it does not need jQuery,   is possible to remove `$` and `window.jQuery` sign?

<img width="982" alt="shot" src="https://user-images.githubusercontent.com/26790174/46854453-736d5880-ce33-11e8-88ab-2eb5b05085ff.png">

**Comment by thedustinsmith** [comment]
Croppie doesn't depend on jquery, but sometimes people find it easier to use jquery plugins rather than vanilla js, that's why we provide it.

I'm confused why you're having problems.  the only way you'd get in that `if` block is if jQuery is defined on the window?  Does zepto define jquery on the window?
