### ISSUE TITLE
TypeError: $(...).croppie is not a function

### ISSUE THREAD

**Issue by Nialcen** [Foliotek/Croppie#637]
## Expected Behavior
I got an image tag with src that may change. On change, I want to make this img "cropable".

## Actual Behavior
When the img tag src changes, croppie throw an error in JS console.

## Steps to Reproduce the Problem

My code : 

```
<script type="text/javascript" src="/js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="/js/croppie.min.js"></script>
<link rel="stylesheet" href="/js/croppie.min.css"></link> 

```
My img is the only tag with this class :
`<img class="lb-image" src="http://fr.militaria-and-co.com/wp-content/uploads/2019/04/53296963_395349407934520_1114204582046597120_n-1.jpg" style="display: block; width: 1138px; height: 856px;">`

```
$('img.lb-image').on('load', function () {
    alert($('img.lb-image').attr('src')); // Alert work well, displaying the right path for my img
    $('img.lb-image').croppie();
});
```
  
## Example Link
* Link : [http://fr.militaria-and-co.com/submit-listing/](http://fr.militaria-and-co.com/submit-listing/)

Go down the page to the "Images" section.
Select an image : it will load and display
Click on your image thumbnail : it will open as a big picture. It's this big picture I want to use to be "cropable"

## Specifications

  - Browser: Chrome and Firefox uptodate
  - Used in wordpress environement

**Comment by srashid5** [comment]
I was experiencing the same issue -`TypeError: $(...) croppie is not a function` 
and I got it fixed by declaring $ as any - `declare var $ : any;` in my angular-cli (typescript) project. I think this lib requires jquery globally

If you're using webpack for bundling, you can also try 
```
plugins: [
    new webpack.ProvidePlugin({
       $: "jquery",
       jQuery: "jquery",
      "window.jQuery": "jquery"
    })
]
```
If you're using vanilla JS and your order of referencing is correct (i.e jquery before croppie), it should work fine, I was able to make croppie work on your code here

https://jsfiddle.net/srashid05/dbt2rcpw/1/
_P.S. the image does not preview because of CORS_

**Comment by Nialcen** [comment]
Thanks. But I solve it in another way, moving my files calls to another section.
